server:
  port: 8080
  apiOnly: False

snptestLegacy:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: (demo) SoySNP 50K subset
  format: vcf

Torkamaneh_Laroche_2017:
  location: assets/glyma.Wm82.gnm2.div.Torkamaneh_Laroche_2017.SNPdata_sub25k.vcf.gz
  name: 102 Canadian accessions
  format: vcf

Song_Yan_2017:
  location: assets/glyma.Wm82.gnm1.div.Song_Yan_2017.SNPs.parents-progeny.vcf.gz
  name: SoyNAM parents and progeny
  format: vcf

Song_Hyten_2015:
  location: assets/glyma.Wm82.gnm2.div.Song_Hyten_2015_sub25k.vcf.gz
  name: SoySNP 50K FULL
  format: vcf

Torkamaneh_Laroche_2017:
  location: assets/glyma.Wm82.gnm2.div.Torkamaneh_Laroche_2019.SNPdata_sub25k.vcf.gz
  name: GmHapMap Data
  format: vcf

Jeong_Moon_2019:
  location: assets/glyma.Wm82.gnm2.div.Jeong_Moon_2019.SNPdata_sub25k.vcf.gz
  name: 4234 Korean accessions using Axiom SoyaSNP array
  format: vcf

Lee_Jeong_2015:
  location: assets/glyma.Wm82.gnm2.div.Lee_Jeong_2015.SNPdata_sub25k.vcf.gz
  name: 222 Korean accessions using Axiom SoyaSNP array
  format: vcf

Valliyodan_Brown_2021:
  location: assets/glyma.Wm82.gnm2.div.Valliyodan_Brown_2021.USB481_sub25k.vcf.gz
  name: USB 481
  format: vcf 

Wei_Mesquita_2017:
  location: assets/glyma.Wm82.gnm2.div.Wei_Mesquita_2017.SNPdata_sub25k.vcf.gz
  name: 374 US and Brazilian accessions
  format: vcf 
